import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const Items = styled.ul`
  display: flex;
  padding: 0;
  margin: 0;
`;

const Item = styled.li`
  list-style-type: none;
`;
const Header = ({}) => {
  return (
    <header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Items>
          <Item>
            <Link href="/">Index</Link>
          </Item>
          <Item>
            <Link href="/page2">Page 2</Link>
          </Item>
          <Item>
            <Link href="/page3">Page 3</Link>
          </Item>
        </Items>
      </nav>
    </header>
  );
};

export default Header;
