import Head from "next/head";
import styles from "styles/Home.module.css";
import Link from "next/link";

const Header = ({}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/page2">Page 2</Link>
        </li>
        <li>
          <Link href="/page3">Page 3</Link>
        </li>
      </ul>
    </div>
  );
};

export default Header;
